export const COFFEE_LIST_REQUEST = 'COFFEE_LIST_REQUEST';
export const COFFEE_LIST_SUCCESS = 'COFFEE_LIST_SUCCESS';
export const COFFEE_LIST_FAIL = 'COFFEE_LIST_FAIL';

export const COFFEE_SINGLE_REQUEST = 'COFFEE_SINGLE_REQUEST';
export const COFFEE_SINGLE_SUCCESS = 'COFFEE_SINGLE_SUCCESS';
export const COFFEE_SINGLE_FAIL = 'COFFEE_SINGLE_FAIL';
