export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_GET_SECRET_REQUEST = 'ORDER_GET_SECRET_REQUEST';
export const ORDER_GET_SECRET_SUCCESS = 'ORDER_GET_SECRET_SUCCESS';
export const ORDER_GET_SECRET_FAIL = 'ORDER_GET_SECRET_FAIL';

export const ORDER_CONFIRM_REQUEST = 'ORDER_CONFIRM_REQUEST';
export const ORDER_CONFIRM_SUCCESS = 'ORDER_CONFIRM_SUCCESS';
export const ORDER_CONFIRM_FAIL = 'ORDER_CONFIRM_FAIL';

export const ORDER_ADD_DELIVERY_REQUEST = 'ORDER_ADD_DELIVERY_REQUEST';
export const ORDER_ADD_DELIVERY_SUCCESS = 'ORDER_ADD_DELIVERY_SUCCESS';
export const ORDER_ADD_DELIVERY_FAIL = 'ORDER_ADD_DELIVERY_FAIL';

export const ORDER_STRIPE_PAY_REQUEST = 'ORDER_STRIPE_PAY_REQUEST';
export const ORDER_STRIPE_PAY_SUCCESS = 'ORDER_STRIPE_PAY_SUCCESS';
export const ORDER_STRIPE_PAY_FAIL = 'ORDER_STRIPE_PAY_FAIL';
