// export const COFFEE_LIST_REQUEST = 'COFFEE_LIST_REQUEST';
// export const COFFEE_LIST_SUCCESS = 'COFFEE_LIST_SUCCESS';
// export const COFFEE_LIST_FAIL = 'COFFEE_LIST_FAIL';

export const ROASTER_SINGLE_REQUEST = 'ROASTER_SINGLE_REQUEST';
export const ROASTER_SINGLE_SUCCESS = 'ROASTER_SINGLE_SUCCESS';
export const ROASTER_SINGLE_FAIL = 'ROASTER_SINGLE_FAIL';
